version: "3"
services:
  maven:
    image: maven:3.5-jdk-8-slim
    volumes:
      - ./:/usr/src
      - ~/.m2:/var/maven/.m2
  node:
    image: "opendigitaleducation/node:18-alpine-pnpm"
    user: "node"
    working_dir: /home/node/app
    network_mode: host
    environment:
      - TIPTAP_PRO_TOKEN 
    volumes:
      - ./:/home/node/app
      - ~/.pnpm:/.pnpm
      - ~/.npm:/.npm
      - ~/.cache:/.cache
